# ===========================
# ConectaTech API - Perfil DEV
# ===========================

# PostgreSQL (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/conectatech
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA - mostrar SQL em dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT (valor apenas para desenvolvimento local)
jwt.secret=ConectaTechDevSecretKey2026UNPMossoroExtensaoProjetoSeguroDev

# CORS
cors.allowed-origins=*

# Logging verbose
logging.level.br.com.unp.conectatech=DEBUG
logging.level.org.springframework.security=DEBUG

# Email (Brevo SMTP para dev)
spring.mail.host=${MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from=${MAIL_FROM:noreply@conectatech.com}
